### ISSUE TITLE
Abfallkalender funktioniert nicht mehr

### ISSUE THREAD

**Issue by scharrin2** [svethi/LoxBerry-CalDAV4Lox#2]
Mein Abfallkalender ist öffentlich.

Wenn ich zum Beispiel die Tage bis zur nächsten Abholung des Papiers ermittle, verwende ich folgende URL
http://loxberry.fritz.box:90/plugins/caldav4lox/caldav.php?calURL=https%3A//calendar.google.com/calendar/ical/r2rvsm7crraqkcvqn9bfi7f2fc%40group.calendar.google.com/private-ec178f514f1483937e120d64ec266bc7/basic.ics&fwdays=30&events=Papier
in meinem virtuellen HTTP-Eingang und mit der Befehlserkennung
\i"fwDay"\i: \"\v
den Wert 27

Wenn ich jetzt ohne irgendeine Änderung in der Config des Miniservers das Plugin von 1.0.2 auf 1.9.1.7 aktualisiere, bekomme ich in Loxone hierfür den Wert 0.

Die Ursache kann ich leider nicht finden, da sowohl das CalDAV4Lox Plugin die richtigen Werte erhält, sowie das Plugin CommandRecognition.

Ich sehe nur, dass die Zahlenwerte beim Beta-Plugin in Anführungszeichen stehen!

Ich bin jetzt wieder auf die Version 1.0.2 zurückgegangen und die Abfrage funktioniert wieder ohne Probleme.

Viele Grüße,
Christian

**Comment by scharrin2** [comment]
Ich habe jetzt nochmal die Beta-Version installiert und auch die Befehlserkennung auf
\i"fwDay"\i: "\v"
geändert.

Jetzt scheint es zu gehen - oder aber ich bekomme die Werte noch aus dem Cache - ich werde es mal beobachten.

Was sich definitiv geändert hat, ist dass die Zahlenwerte in Anführungszeichen stehen.

Viele Grüße,
Christian

**Comment by svethi** [comment]
Ich gebe immer an, dass im Forum zu antworten ist, da ich hier nicht mitlese.
Nun, bei einer Beta kann mal was nicht passen. Das ist auch nicht immer gleich ein Issue. Der Wert im JSON ist auch noch in Anführungszeichen richtig. Wenn das natürlich anders ausgelesen wird wie bei Loxone, kann dies schon eine Änderung nach sich ziehen.
Grund für das Ganze sind immer mal wieder fehlerhaft JSON Ausgaben gewesen, da ich das JSON vorher immer selber geschrieben habe. Ich bin in der Version auf json_encode umgestiegen. Dies hat gleich mehrere solcher "Änderungen" hervorgerufen. Z.B. auch, dass ohne zusätzliche Option Zahlenwerte auch gequotet wurden. Das gefiel mir aber auch nicht und ich habe da bereits eine weitere Option eingefügt, die mit dem nächsten PreRelease/Release dann greift und die Zahlenwerte wieder ungequotet ins JSON schreibt. Also bei den nächsten Versionen wieder aufpassen, da ist das dann wieder wie früher.
